[package]
name = "albion-translator"
version = "0.1.0"
default-run = "albion-translator"
description = "Albion Online chat translator overlay"
authors = ["synth"]
edition = "2021"

[lib]
name = "albion_translator_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
pcap = { version = "2", features = ["capture-stream"] }
thiserror = "2"
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12", features = ["json"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
lingua = { version = "1.8.0", features = ["chinese", "japanese", "korean", "russian", "arabic", "thai", "portuguese", "spanish", "french", "german", "turkish", "english"] }
ct2rs = "0.10.0"
dirs = "6.0.0"
ctrlc = "3.5.2"
albion-network-lib = { git = "https://github.com/beemerwt/albion-network-lib.git", version = "0.1.0" }

