// Shared language list for Albion Online Translator.
// Codes are Google Translate API codes — the backend passes them straight
// through to the free Google endpoint, so any supported code works.
// Both the main app picker and the user-translator iframe import this so
// the two selects never drift apart.
//
// Display format: "Native Name (English)" — the native name helps speakers
// find their language, the English name helps everyone else.

export const languages = [
  { code: "en", name: "English" },
  { code: "es", name: "Español (Spanish)" },
  { code: "pt", name: "Português (Portuguese)" },
  { code: "zh", name: "中文（简体）(Chinese Simplified)" },
  { code: "zh-TW", name: "中文（繁體）(Chinese Traditional)" },
  { code: "ru", name: "Русский (Russian)" },
  { code: "de", name: "Deutsch (German)" },
  { code: "fr", name: "Français (French)" },
  { code: "ko", name: "한국어 (Korean)" },
  { code: "ja", name: "日本語 (Japanese)" },
  { code: "tr", name: "Türkçe (Turkish)" },
  { code: "it", name: "Italiano (Italian)" },
  { code: "pl", name: "Polski (Polish)" },
  { code: "uk", name: "Українська (Ukrainian)" },
  { code: "nl", name: "Nederlands (Dutch)" },
  { code: "sv", name: "Svenska (Swedish)" },
  { code: "no", name: "Norsk (Norwegian)" },
  { code: "da", name: "Dansk (Danish)" },
  { code: "fi", name: "Suomi (Finnish)" },
  { code: "cs", name: "Čeština (Czech)" },
  { code: "sk", name: "Slovenčina (Slovak)" },
  { code: "hu", name: "Magyar (Hungarian)" },
  { code: "ro", name: "Română (Romanian)" },
  { code: "bg", name: "Български (Bulgarian)" },
  { code: "el", name: "Ελληνικά (Greek)" },
  { code: "hr", name: "Hrvatski (Croatian)" },
  { code: "sr", name: "Српски (Serbian)" },
  { code: "sl", name: "Slovenščina (Slovenian)" },
  { code: "lt", name: "Lietuvių (Lithuanian)" },
  { code: "lv", name: "Latviešu (Latvian)" },
  { code: "et", name: "Eesti (Estonian)" },
  { code: "ar", name: "العربية (Arabic)" },
  { code: "he", name: "עברית (Hebrew)" },
  { code: "hi", name: "हिन्दी (Hindi)" },
  { code: "bn", name: "বাংলা (Bengali)" },
  { code: "th", name: "ไทย (Thai)" },
  { code: "vi", name: "Tiếng Việt (Vietnamese)" },
  { code: "id", name: "Bahasa Indonesia (Indonesian)" },
  { code: "ms", name: "Bahasa Melayu (Malay)" },
  { code: "fil", name: "Filipino" },
  { code: "fa", name: "فارسی (Persian)" },
  { code: "ur", name: "اردو (Urdu)" },
  { code: "ka", name: "ქართული (Georgian)" },
  { code: "hy", name: "Հայերեն (Armenian)" },
  { code: "az", name: "Azərbaycan (Azerbaijani)" },
  { code: "kk", name: "Қазақ (Kazakh)" },
  { code: "uz", name: "Oʻzbek (Uzbek)" },
  { code: "mn", name: "Монгол (Mongolian)" },
  { code: "ne", name: "नेपाली (Nepali)" },
  { code: "si", name: "සිංහල (Sinhala)" },
  { code: "km", name: "ខ្មែរ (Khmer)" },
  { code: "lo", name: "ລາວ (Lao)" },
  { code: "my", name: "မြန်မာ (Burmese)" },
  { code: "ta", name: "தமிழ் (Tamil)" },
  { code: "te", name: "తెలుగు (Telugu)" },
  { code: "ml", name: "മലയാളം (Malayalam)" },
  { code: "kn", name: "ಕನ್ನಡ (Kannada)" },
  { code: "gu", name: "ગુજરાતી (Gujarati)" },
  { code: "mr", name: "मराठी (Marathi)" },
  { code: "pa", name: "ਪੰਜਾਬੀ (Punjabi)" },
  { code: "af", name: "Afrikaans" },
  { code: "sw", name: "Kiswahili (Swahili)" },
  { code: "zu", name: "isiZulu (Zulu)" },
  { code: "yo", name: "Yorùbá (Yoruba)" },
  { code: "ig", name: "Igbo" },
  { code: "am", name: "አማርኛ (Amharic)" },
  { code: "sq", name: "Shqip (Albanian)" },
  { code: "bs", name: "Bosanski (Bosnian)" },
  { code: "mk", name: "Македонски (Macedonian)" },
  { code: "is", name: "Íslenska (Icelandic)" },
  { code: "ga", name: "Gaeilge (Irish)" },
  { code: "cy", name: "Cymraeg (Welsh)" },
  { code: "eu", name: "Euskara (Basque)" },
  { code: "ca", name: "Català (Catalan)" },
  { code: "gl", name: "Galego (Galician)" },
  { code: "mt", name: "Malti (Maltese)" },
  { code: "la", name: "Latina (Latin)" },
];
